# Custom Language File for Launcher Customizer

[ejs.app]
title = "KEVENT Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/S0KAA/KEVENT-Launcher"
mediaTwitterURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "#"